package cryptorefills

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
)

// This customer-safe catalogue is shared with the frontend. Never translate
// by blindly rendering moreDetails.reason or arbitrary upstream response text.
var problemCatalogJSON = func() []byte {
	const b64 = "ewogICJBTU9VTlRfTEVTU19USEVOX01JTklNVU1fQUxMT1dFRCI6IHsKICAgICJzY29wZSI6ICJvcmRlciIsCiAgICAibWVzc2FnZSI6ICJUaGUgb3JkZXIgdG90YWwgaXMgYmVsb3cgdGhlIG1pbmltdW0gcGF5bWVudCBhbW91bnQuIEluY3JlYXNlIHRoZSBhbW91bnQgb3IgYWRqdXN0IHRoZSBjYXJ0IGJlZm9yZSB0cnlpbmcgYWdhaW4uIgogIH0sCiAgIk1BWElNVU1fQU1PVU5UX1BFUl9PUkRFUl9FWENFRURFRCI6IHsKICAgICJzY29wZSI6ICJvcmRlciIsCiAgICAibWVzc2FnZSI6ICJUaGUgb3JkZXIgdG90YWwgZXhjZWVkcyB0aGUgcGVyLW9yZGVyIG1heGltdW0uIFJlZHVjZSB0aGUgb3JkZXIgYW1vdW50IGJlZm9yZSB0cnlpbmcgYWdhaW4uIgogIH0sCiAgIkRBSUxZX1NQRU5ESU5HX0xJTUlUX0VYQ0VFREVEIjogewogICAgInNjb3BlIjogImFjY291bnQiLAogICAgIm1lc3NhZ2UiOiAiWW91ciBDcnlwdG9yZWZpbGxzIGRhaWx5IHNwZW5kaW5nIGxpbWl0IGhhcyBiZWVuIHJlYWNoZWQuIFdhaXQgZm9yIHRoYXQgbGltaXQgdG8gcmVzZXQgb3IgcmV2aWV3IHlvdXIgYWNjb3VudCB0aWVyLiBTcGxpdHRpbmcgdGhlIGNhcnQgZG9lcyBub3QgYnlwYXNzIHRoaXMgbGltaXQuIgogIH0sCiAgIk1PTlRITFlfU1BFTkRJTkdfTElNSVRfRVhDRUVERUQiOiB7CiAgICAic2NvcGUiOiAiYWNjb3VudCIsCiAgICAibWVzc2FnZSI6ICJZb3VyIENyeXB0b3JlZmlsbHMgbW9udGhseSBzcGVuZGluZyBsaW1pdCBoYXMgYmVlbiByZWFjaGVkLiBXYWl0IGZvciB0aGF0IGxpbWl0IHRvIHJlc2V0IG9yIHJldmlldyB5b3VyIGFjY291bnQgdGllci4gU3BsaXR0aW5nIHRoZSBjYXJ0IGRvZXMgbm90IGJ5cGFzcyB0aGlzIGxpbWl0LiIKICB9LAogICJQUk9EVUNUX0NPVU5UX0VYQ0VFREVEIjogewogICAgInNjb3BlIjogIm9yZGVyIiwKICAgICJtZXNzYWdlIjogIlRoZSBjYXJ0IGNvbnRhaW5zIG1vcmUgcHJvZHVjdHMgdGhhbiBhbGxvd2VkIGluIG9uZSBvcmRlci4gUmVkdWNlIHRoZSBwcm9kdWN0IHF1YW50aXR5IGJlZm9yZSB0cnlpbmcgYWdhaW4uIgogIH0sCiAgIk1VTFRJUExFX0xJTUlURURfUFJPRFVDVF9TQU1FX09SREVSIjogewogICAgInNjb3BlIjogIm9yZGVyIiwKICAgICJtZXNzYWdlIjogIlRoaXMgb3JkZXIgY29udGFpbnMgbW9yZSB0aGFuIG9uZSBsaW1pdGVkIHByb2R1Y3QuIFJlbW92ZSB0aGUgY29uZmxpY3RpbmcgbGltaXRlZCBwcm9kdWN0cyBhbmQgcmVjaGVjayB0aGUgY2FydC4iCiAgfSwKICAiTk9UX0FWQUlMQUJMRV9QUk9EVUNUIjogewogICAgInNjb3BlIjogIml0ZW0iLAogICAgIm1lc3NhZ2UiOiAiVGhpcyBwcm9kdWN0IGlzIG5vIGxvbmdlciBhdmFpbGFibGUgaW4gdGhlIENyeXB0b3JlZmlsbHMgY2F0YWxvZ3VlLiBSZW1vdmUgaXQgb3IgY2hvb3NlIGFub3RoZXIgcHJvZHVjdC4iCiAgfSwKICAiT1VUX09GX1NUT0NLIjogewogICAgInNjb3BlIjogIml0ZW0iLAogICAgIm1lc3NhZ2UiOiAiVGhpcyBwcm9kdWN0IGlzIG91dCBvZiBzdG9jay4gUmVtb3ZlIGl0IG9yIGNob29zZSBhbm90aGVyIHByb2R1Y3Q7IGF2YWlsYWJpbGl0eSBtYXkgY2hhbmdlIGxhdGVyLiIKICB9LAogICJOT1RfQUNUSVZFIjogewogICAgInNjb3BlIjogIml0ZW0iLAogICAgIm1lc3NhZ2UiOiAiVGhpcyBwcm9kdWN0IGlzIGluYWN0aXZlIG9yIHRlbXBvcmFyaWx5IHBhdXNlZC4gQ2hvb3NlIGFub3RoZXIgcHJvZHVjdCBvciBjaGVjayBhZ2FpbiBsYXRlci4iCiAgfSwKICAiSU5WQUxJRF9CRU5FRklDSUFSWV9BQ0NPVU5UIjogewogICAgInNjb3BlIjogImlucHV0IiwKICAgICJtZXNzYWdlIjogIlRoZSBkZWxpdmVyeSBlbWFpbCwgcGhvbmUgbnVtYmVyIG9yIGJlbmVmaWNpYXJ5IGFjY291bnQgaXMgbm90IGFjY2VwdGVkLiBDb3JyZWN0IHRoZSBkZWxpdmVyeSBkZXRhaWxzIGJlZm9yZSB0cnlpbmcgYWdhaW4uIgogIH0sCiAgIk5PVF9BTExPV0VEX1BBWU1FTlRfVklBIjogewogICAgInNjb3BlIjogInBheW1lbnQiLAogICAgIm1lc3NhZ2UiOiAiVGhlIHNlbGVjdGVkIHBheW1lbnQgb3B0aW9uIGlzIG5vdCBhbGxvd2VkIGZvciB0aGlzIG9yZGVyLiBDaG9vc2UgYW5vdGhlciBwYXltZW50IG9wdGlvbiBvZmZlcmVkIGJ5IHRoaXMgc2hvcCwgb3IgY29udGFjdCBzdXBwb3J0IGlmIG5vbmUgaXMgYXZhaWxhYmxlLiIKICB9LAogICJVTlNVUFBPUlRFRF9QUk9UT0NPTF9DT0lOX0NPTUJJTkFUSU9OIjogewogICAgInNjb3BlIjogInBheW1lbnQiLAogICAgIm1lc3NhZ2UiOiAiVGhpcyBwYXltZW50IG1ldGhvZCBhbmQgbmV0d29yayBjb21iaW5hdGlvbiBpcyBub3Qgc3VwcG9ydGVkLiBDaG9vc2UgYW5vdGhlciBwYXltZW50IG9wdGlvbiBvZmZlcmVkIGJ5IHRoaXMgc2hvcCwgb3IgY29udGFjdCBzdXBwb3J0LiIKICB9LAogICJMT0dJTl9SRVFVSVJFRCI6IHsKICAgICJzY29wZSI6ICJhY2NvdW50IiwKICAgICJtZXNzYWdlIjogIlRoZXNlIHByb2R1Y3RzIHJlcXVpcmUgYSBzaWduZWQtaW4gQ3J5cHRvcmVmaWxscyBhY2NvdW50LiBTaWduIGluIHRvIENyeXB0b3JlZmlsbHMgYmVmb3JlIHRyeWluZyBhZ2Fpbi4gQ29ubmVjdGluZyBhIE5pbWlxIHdhbGxldCBoZXJlIGlzIG5vdCB0aGUgc2FtZSBhcyBzaWduaW5nIGluIHRoZXJlLiIKICB9LAogICJDT1VQT05fUkVRVUlSRVNfTE9HSU4iOiB7CiAgICAic2NvcGUiOiAiYWNjb3VudCIsCiAgICAibWVzc2FnZSI6ICJUaGlzIENyeXB0b3JlZmlsbHMgY291cG9uIHJlcXVpcmVzIGEgc2lnbmVkLWluIENyeXB0b3JlZmlsbHMgYWNjb3VudC4gU2lnbiBpbiB0aGVyZSwgb3IgcmVtb3ZlIHRoZSBjb3Vwb24gYmVmb3JlIHRyeWluZyBhZ2Fpbi4iCiAgfSwKICAiQ09VUE9OX05PVF9GT1VORCI6IHsKICAgICJzY29wZSI6ICJjb3Vwb24iLAogICAgIm1lc3NhZ2UiOiAiVGhlIENyeXB0b3JlZmlsbHMgY291cG9uIHdhcyBub3QgZm91bmQuIENoZWNrIHRoZSBjb2RlIG9yIHJlbW92ZSBpdCBiZWZvcmUgdHJ5aW5nIGFnYWluLiIKICB9LAogICJDT1VQT05fTk9UX0FDVElWRSI6IHsKICAgICJzY29wZSI6ICJjb3Vwb24iLAogICAgIm1lc3NhZ2UiOiAiVGhlIENyeXB0b3JlZmlsbHMgY291cG9uIGlzIG5vdCBhY3RpdmUgeWV0LiBXYWl0IHVudGlsIGl0IGJlY29tZXMgYWN0aXZlIG9yIHJlbW92ZSBpdC4iCiAgfSwKICAiQ09VUE9OX0FMUkVBRFlfU1BFTlQiOiB7CiAgICAic2NvcGUiOiAiY291cG9uIiwKICAgICJtZXNzYWdlIjogIlRoaXMgQ3J5cHRvcmVmaWxscyBjb3Vwb24gaGFzIGFscmVhZHkgYmVlbiByZWRlZW1lZCBieSB0aGlzIGFjY291bnQuIFJlbW92ZSBpdCBvciB1c2UgYW5vdGhlciBlbGlnaWJsZSBjb3Vwb24uIgogIH0sCiAgIkNPVVBPTl9NQVhfVVNBR0VfUkVBQ0hFRCI6IHsKICAgICJzY29wZSI6ICJjb3Vwb24iLAogICAgIm1lc3NhZ2UiOiAiVGhpcyBDcnlwdG9yZWZpbGxzIGNvdXBvbiBoYXMgcmVhY2hlZCBpdHMgdG90YWwgdXNhZ2UgbGltaXQuIFJlbW92ZSBpdCBvciB1c2UgYW5vdGhlciBlbGlnaWJsZSBjb3Vwb24uIgogIH0sCiAgIkNPVVBPTl9FWFBJUkVEIjogewogICAgInNjb3BlIjogImNvdXBvbiIsCiAgICAibWVzc2FnZSI6ICJUaGUgQ3J5cHRvcmVmaWxscyBjb3Vwb24gaGFzIGV4cGlyZWQuIFJlbW92ZSBpdCBvciB1c2UgYW5vdGhlciBlbGlnaWJsZSBjb3Vwb24uIgogIH0sCiAgIkNPVVBPTl9CRUxPV19NSU5fQU1PVU5UIjogewogICAgInNjb3BlIjogImNvdXBvbiIsCiAgICAibWVzc2FnZSI6ICJUaGUgb3JkZXIgaXMgYmVsb3cgdGhpcyBDcnlwdG9yZWZpbGxzIGNvdXBvbuKAmXMgbWluaW11bSBhbW91bnQuIEFkanVzdCB0aGUgY2FydCBvciByZW1vdmUgdGhlIGNvdXBvbi4iCiAgfSwKICAiQ09VUE9OX05PVF9WQUxJRF9GT1JfVVNFUiI6IHsKICAgICJzY29wZSI6ICJjb3Vwb24iLAogICAgIm1lc3NhZ2UiOiAiVGhpcyBDcnlwdG9yZWZpbGxzIGNvdXBvbiBpcyBub3QgdmFsaWQgZm9yIHlvdXIgYWNjb3VudC4gUmVtb3ZlIGl0IG9yIHVzZSBhIGNvdXBvbiBhdmFpbGFibGUgdG8geW91LiIKICB9LAogICJDT1VQT05fTk9UX1ZBTElEX0ZPUl9DQVRFR09SWSI6IHsKICAgICJzY29wZSI6ICJjb3Vwb24iLAogICAgIm1lc3NhZ2UiOiAiVGhpcyBDcnlwdG9yZWZpbGxzIGNvdXBvbiBkb2VzIG5vdCBhcHBseSB0byB0aGUgc2VsZWN0ZWQgcHJvZHVjdCBjYXRlZ29yaWVzLiBDaGFuZ2UgdGhlIHNlbGVjdGlvbiBvciByZW1vdmUgdGhlIGNvdXBvbi4iCiAgfSwKICAiQ09VUE9OX05PVF9WQUxJRF9GT1JfS0lORCI6IHsKICAgICJzY29wZSI6ICJjb3Vwb24iLAogICAgIm1lc3NhZ2UiOiAiVGhpcyBDcnlwdG9yZWZpbGxzIGNvdXBvbiBkb2VzIG5vdCBhcHBseSB0byB0aGUgc2VsZWN0ZWQgcHJvZHVjdCBraW5kLiBDaGFuZ2UgdGhlIHNlbGVjdGlvbiBvciByZW1vdmUgdGhlIGNvdXBvbi4iCiAgfSwKICAiQ09VUE9OX05PVF9WQUxJRF9GT1JfQlJBTkQiOiB7CiAgICAic2NvcGUiOiAiY291cG9uIiwKICAgICJtZXNzYWdlIjogIlRoaXMgQ3J5cHRvcmVmaWxscyBjb3Vwb24gZG9lcyBub3QgYXBwbHkgdG8gdGhlIHNlbGVjdGVkIGJyYW5kcy4gQ2hhbmdlIHRoZSBzZWxlY3Rpb24gb3IgcmVtb3ZlIHRoZSBjb3Vwb24uIgogIH0sCiAgIkNPVVBPTl9OT1RfVkFMSURfRk9SX0NPVU5UUlkiOiB7CiAgICAic2NvcGUiOiAiY291cG9uIiwKICAgICJtZXNzYWdlIjogIlRoaXMgQ3J5cHRvcmVmaWxscyBjb3Vwb24gaXMgbm90IHZhbGlkIGluIHRoZSBvcmRlciBjb3VudHJ5LiBDaGVjayB0aGUgaW50ZW5kZWQgY291bnRyeSBvciByZW1vdmUgdGhlIGNvdXBvbi4iCiAgfSwKICAiQ09VUE9OX05PVF9WQUxJRF9GT1JfU1RPUkUiOiB7CiAgICAic2NvcGUiOiAiY291cG9uIiwKICAgICJtZXNzYWdlIjogIlRoaXMgQ3J5cHRvcmVmaWxscyBjb3Vwb24gaXMgbm90IHZhbGlkIGZvciB0aGUgcmVxdWVzdGVkIHN0b3JlIG9yIHJlZ2lvbi4gQ2hlY2sgdGhlIGludGVuZGVkIHN0b3JlIG9yIHJlbW92ZSB0aGUgY291cG9uLiIKICB9LAogICJLWUNfTUlTU0lORyI6IHsKICAgICJzY29wZSI6ICJhY2NvdW50IiwKICAgICJtZXNzYWdlIjogIkNyeXB0b3JlZmlsbHMgcmVxdWlyZXMgaWRlbnRpdHkgdmVyaWZpY2F0aW9uIGZvciB0aGlzIG9yZGVyIG9yIHNwZW5kaW5nIHRpZXIuIE9wZW4geW91ciBDcnlwdG9yZWZpbGxzIGFjY291bnQgYW5kIGNvbXBsZXRlIHZlcmlmaWNhdGlvbiBiZWZvcmUgdHJ5aW5nIGFnYWluLiIKICB9LAogICJLWUNfUEVORElORyI6IHsKICAgICJzY29wZSI6ICJhY2NvdW50IiwKICAgICJtZXNzYWdlIjogIllvdXIgQ3J5cHRvcmVmaWxscyBpZGVudGl0eSB2ZXJpZmljYXRpb24gaXMgYWxyZWFkeSBpbiBwcm9ncmVzcy4gSXQgdHlwaWNhbGx5IGNvbXBsZXRlcyB3aXRoaW4gMjAgbWludXRlcyBidXQgbWF5IHRha2UgdXAgdG8gNDggaG91cnMuIFdhaXQgZm9yIHRoZSByZXN1bHQ7IGNvbnRhY3QgQ3J5cHRvcmVmaWxscyBzdXBwb3J0IGlmIGl0IHJlbWFpbnMgcGVuZGluZyBiZXlvbmQgdGhhdC4iCiAgfSwKICAiVkVSSUZJQ0FUSU9OX1JFUVVJUkVEIjogewogICAgInNjb3BlIjogImFjY291bnQiLAogICAgIm1lc3NhZ2UiOiAiQ3J5cHRvcmVmaWxscyByZXF1aXJlcyBhZGRpdGlvbmFsIHZlcmlmaWNhdGlvbiBiZWZvcmUgdGhpcyBvcmRlciBjYW4gcHJvY2VlZC4gUmV2aWV3IHlvdXIgQ3J5cHRvcmVmaWxscyBhY2NvdW50IGFuZCBjb250YWN0IENyeXB0b3JlZmlsbHMgc3VwcG9ydCBpZiB0aGlzIHBlcnNpc3RzLiIKICB9LAogICJTVVNQRU5ERURfQ09JTiI6IHsKICAgICJzY29wZSI6ICJwYXltZW50IiwKICAgICJtZXNzYWdlIjogIlRoZSBzZWxlY3RlZCBwYXltZW50IGNvaW4gaXMgdGVtcG9yYXJpbHkgc3VzcGVuZGVkIGJ5IENyeXB0b3JlZmlsbHMuIFdhaXQgdW50aWwgaXQgaXMgYXZhaWxhYmxlIGFnYWluLCBvciBjaG9vc2UgYW5vdGhlciBwYXltZW50IG9wdGlvbiBvZmZlcmVkIGJ5IHRoaXMgc2hvcC4iCiAgfSwKICAiU1VTUEVOREVEX05FVFdPUksiOiB7CiAgICAic2NvcGUiOiAicGF5bWVudCIsCiAgICAibWVzc2FnZSI6ICJUaGUgc2VsZWN0ZWQgcGF5bWVudCBuZXR3b3JrIGlzIHRlbXBvcmFyaWx5IHN1c3BlbmRlZCBieSBDcnlwdG9yZWZpbGxzLiBXYWl0IHVudGlsIGl0IGlzIGF2YWlsYWJsZSBhZ2Fpbiwgb3IgY2hvb3NlIGFub3RoZXIgcGF5bWVudCBvcHRpb24gb2ZmZXJlZCBieSB0aGlzIHNob3AuIgogIH0KfQo="
	data, _ := base64.StdEncoding.DecodeString(b64)
	return data
}()

type ProblemInfo struct {
	Scope   string `json:"scope"`
	Message string `json:"message"`
}

var problemCatalog = func() map[string]ProblemInfo {
	if len(problemCatalogJSON) == 0 {
		return map[string]ProblemInfo{}
	}
	var out map[string]ProblemInfo
	if err := json.Unmarshal(problemCatalogJSON, &out); err != nil {
		return map[string]ProblemInfo{}
	}
	return out
}()

func LookupProblem(code string) (ProblemInfo, bool) {
	code = strings.ToUpper(strings.TrimSpace(code))
	if code == "PRODUCT_NOT_AVAILABLE" {
		code = "NOT_AVAILABLE_PRODUCT"
	}
	info, ok := problemCatalog[code]
	return info, ok
}

func ProblemMessage(code string) string {
	if info, ok := LookupProblem(code); ok {
		return info.Message
	}
	switch code {
	case "INVALID_DENOMINATION", "INVALID_PRODUCT_VALUE":
		return "The selected amount is not available for this item. Choose another amount."
	case "AMOUNT_TOO_LOW":
		return "The amount is below this item's minimum. Increase the amount."
	case "AMOUNT_TOO_HIGH":
		return "The amount is above this item's maximum. Reduce the amount."
	case "COUNTRY_NOT_SUPPORTED":
		return "This item is not sold in the selected country. Check the intended country."
	}
	return "Cryptorefills could not approve this request. Review the order and contact support before trying again."
}

// responseProblems handles the same envelope on success and HTTP-error paths.
// Invalid problem arrays are protocol failures, never permission to order.
func responseProblems(raw []byte, status int) error {
	var obj map[string]json.RawMessage
	if json.Unmarshal(raw, &obj) != nil || obj == nil {
		return nil
	}
	p, present := obj["problems"]
	if !present {
		return nil
	}
	p = bytes.TrimSpace(p)
	// Observed live success fixtures use null for an empty list. The validation
	// decoder still requires a valid positive quoted amount before success.
	if bytes.Equal(p, []byte("null")) {
		return nil
	}
	if len(p) == 0 || p[0] != '[' {
		return fmt.Errorf("supplier response has invalid problems array")
	}
	var problems []Problem
	if err := json.Unmarshal(p, &problems); err != nil {
		return fmt.Errorf("supplier response has malformed problems: %w", err)
	}
	for _, problem := range problems {
		if !isProblemCode(problem.Code) {
			return fmt.Errorf("supplier response has invalid problem code")
		}
	}
	if len(problems) == 0 {
		return nil
	}
	// A success-looking order identity AND a rejection are contradictory. Do
	// not classify a possibly created order as safely rejected and resend it.
	for _, key := range []string{"order_id", "id"} {
		if v := bytes.TrimSpace(obj[key]); len(v) > 0 && string(v) != "null" && string(v) != `""` {
			return fmt.Errorf("supplier returned both an order identity and problems; outcome unknown")
		}
	}
	// Preserve a top-level suspension as well if a supplier combines envelopes.
	var detail string
	if json.Unmarshal(obj["detail"], &detail) == nil && isProblemCode(detail) {
		found := false
		for _, p := range problems {
			if p.Code == detail {
				found = true
			}
		}
		if !found {
			var more any
			_ = json.Unmarshal(obj["moreDetails"], &more)
			problems = append(problems, Problem{Code: detail, Details: more})
		}
	}
	return &ProblemError{Problems: problems, HTTPStatus: status}
}
