/* countries.js — the full shop country list.
 *
 * The old UI offered ~15 hand-picked countries even though the backend
 * (and the CryptoRefills catalog behind it) accepts ANY ISO 3166-1 alpha-2
 * code. This module lists every commonly purchasable country so the
 * storefront's country picker matches the supplier's real coverage.
 *
 * Names are the English short names; flags are derived from the code by
 * util.flag() and localized names (when available) by util.countryName().
 */

// Shown first in the picker (biggest shop markets).
const POPULAR = ['TR', 'US', 'GB', 'DE', 'FR', 'ES', 'IT', 'NL', 'CA', 'BR', 'IN', 'AU', 'JP', 'PL', 'MX'];

// Full ISO 3166-1 alpha-2 list (excluding the popular pins above to avoid
// duplicates in the alphabetical group).
const COUNTRIES = [
  ['TR', 'Türkiye'],
  ['US', 'United States'],
  ['GB', 'United Kingdom'],
  ['DE', 'Germany'],
  ['FR', 'France'],
  ['ES', 'Spain'],
  ['IT', 'Italy'],
  ['NL', 'Netherlands'],
  ['CA', 'Canada'],
  ['BR', 'Brazil'],
  ['IN', 'India'],
  ['AU', 'Australia'],
  ['JP', 'Japan'],
  ['PL', 'Poland'],
  ['MX', 'Mexico'],
  ['AD', 'Andorra'],
  ['AE', 'United Arab Emirates'],
  ['AF', 'Afghanistan'],
  ['AG', 'Antigua & Barbuda'],
  ['AL', 'Albania'],
  ['AM', 'Armenia'],
  ['AO', 'Angola'],
  ['AR', 'Argentina'],
  ['AT', 'Austria'],
  ['AZ', 'Azerbaijan'],
  ['BA', 'Bosnia & Herzegovina'],
  ['BB', 'Barbados'],
  ['BD', 'Bangladesh'],
  ['BE', 'Belgium'],
  ['BF', 'Burkina Faso'],
  ['BG', 'Bulgaria'],
  ['BH', 'Bahrain'],
  ['BI', 'Burundi'],
  ['BJ', 'Benin'],
  ['BN', 'Brunei'],
  ['BO', 'Bolivia'],
  ['BS', 'Bahamas'],
  ['BT', 'Bhutan'],
  ['BW', 'Botswana'],
  ['BY', 'Belarus'],
  ['BZ', 'Belize'],
  ['CD', 'DR Congo'],
  ['CF', 'Central African Republic'],
  ['CG', 'Congo'],
  ['CH', 'Switzerland'],
  ['CI', 'Côte d’Ivoire'],
  ['CL', 'Chile'],
  ['CM', 'Cameroon'],
  ['CO', 'Colombia'],
  ['CR', 'Costa Rica'],
  ['CV', 'Cabo Verde'],
  ['CY', 'Cyprus'],
  ['CZ', 'Czechia'],
  ['DJ', 'Djibouti'],
  ['DK', 'Denmark'],
  ['DM', 'Dominica'],
  ['DO', 'Dominican Republic'],
  ['DZ', 'Algeria'],
  ['EC', 'Ecuador'],
  ['EE', 'Estonia'],
  ['EG', 'Egypt'],
  ['ER', 'Eritrea'],
  ['ET', 'Ethiopia'],
  ['FI', 'Finland'],
  ['FJ', 'Fiji'],
  ['FM', 'Micronesia'],
  ['GA', 'Gabon'],
  ['GD', 'Grenada'],
  ['GE', 'Georgia'],
  ['GH', 'Ghana'],
  ['GM', 'Gambia'],
  ['GN', 'Guinea'],
  ['GQ', 'Equatorial Guinea'],
  ['GR', 'Greece'],
  ['GT', 'Guatemala'],
  ['GW', 'Guinea-Bissau'],
  ['GY', 'Guyana'],
  ['HN', 'Honduras'],
  ['HR', 'Croatia'],
  ['HT', 'Haiti'],
  ['HU', 'Hungary'],
  ['ID', 'Indonesia'],
  ['IE', 'Ireland'],
  ['IL', 'Israel'],
  ['IQ', 'Iraq'],
  ['IR', 'Iran'],
  ['IS', 'Iceland'],
  ['JM', 'Jamaica'],
  ['JO', 'Jordan'],
  ['KE', 'Kenya'],
  ['KG', 'Kyrgyzstan'],
  ['KH', 'Cambodia'],
  ['KI', 'Kiribati'],
  ['KM', 'Comoros'],
  ['KN', 'St. Kitts & Nevis'],
  ['KR', 'South Korea'],
  ['KW', 'Kuwait'],
  ['KZ', 'Kazakhstan'],
  ['LA', 'Laos'],
  ['LB', 'Lebanon'],
  ['LC', 'St. Lucia'],
  ['LI', 'Liechtenstein'],
  ['LK', 'Sri Lanka'],
  ['LR', 'Liberia'],
  ['LS', 'Lesotho'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['LV', 'Latvia'],
  ['LY', 'Libya'],
  ['MA', 'Morocco'],
  ['MC', 'Monaco'],
  ['MD', 'Moldova'],
  ['ME', 'Montenegro'],
  ['MG', 'Madagascar'],
  ['MH', 'Marshall Islands'],
  ['MK', 'North Macedonia'],
  ['ML', 'Mali'],
  ['MM', 'Myanmar'],
  ['MN', 'Mongolia'],
  ['MR', 'Mauritania'],
  ['MT', 'Malta'],
  ['MU', 'Mauritius'],
  ['MV', 'Maldives'],
  ['MW', 'Malawi'],
  ['MY', 'Malaysia'],
  ['MZ', 'Mozambique'],
  ['NA', 'Namibia'],
  ['NE', 'Niger'],
  ['NG', 'Nigeria'],
  ['NI', 'Nicaragua'],
  ['NO', 'Norway'],
  ['NP', 'Nepal'],
  ['NR', 'Nauru'],
  ['NZ', 'New Zealand'],
  ['OM', 'Oman'],
  ['PA', 'Panama'],
  ['PE', 'Peru'],
  ['PG', 'Papua New Guinea'],
  ['PH', 'Philippines'],
  ['PK', 'Pakistan'],
  ['PT', 'Portugal'],
  ['PW', 'Palau'],
  ['PY', 'Paraguay'],
  ['QA', 'Qatar'],
  ['RO', 'Romania'],
  ['RS', 'Serbia'],
  ['RW', 'Rwanda'],
  ['SA', 'Saudi Arabia'],
  ['SB', 'Solomon Islands'],
  ['SC', 'Seychelles'],
  ['SD', 'Sudan'],
  ['SE', 'Sweden'],
  ['SG', 'Singapore'],
  ['SI', 'Slovenia'],
  ['SK', 'Slovakia'],
  ['SL', 'Sierra Leone'],
  ['SM', 'San Marino'],
  ['SN', 'Senegal'],
  ['SO', 'Somalia'],
  ['SR', 'Suriname'],
  ['SS', 'South Sudan'],
  ['ST', 'São Tomé & Príncipe'],
  ['SV', 'El Salvador'],
  ['SZ', 'Eswatini'],
  ['TD', 'Chad'],
  ['TG', 'Togo'],
  ['TH', 'Thailand'],
  ['TJ', 'Tajikistan'],
  ['TL', 'Timor-Leste'],
  ['TM', 'Turkmenistan'],
  ['TN', 'Tunisia'],
  ['TO', 'Tonga'],
  ['TT', 'Trinidad & Tobago'],
  ['TV', 'Tuvalu'],
  ['TZ', 'Tanzania'],
  ['UA', 'Ukraine'],
  ['UG', 'Uganda'],
  ['UY', 'Uruguay'],
  ['UZ', 'Uzbekistan'],
  ['VA', 'Vatican City'],
  ['VC', 'St. Vincent & Grenadines'],
  ['VE', 'Venezuela'],
  ['VN', 'Vietnam'],
  ['VU', 'Vanuatu'],
  ['WS', 'Samoa'],
  ['YE', 'Yemen'],
  ['ZA', 'South Africa'],
  ['ZM', 'Zambia'],
  ['ZW', 'Zimbabwe'],
];

// Popular-first ordering used by the picker.
export function orderedCountries() {
  const popular = POPULAR.map((code) => COUNTRIES.find((c) => c[0] === code)).filter(Boolean);
  const rest = COUNTRIES.filter((c) => !POPULAR.includes(c[0]));
  rest.sort((a, b) => a[1].localeCompare(b[1]));
  return { popular, rest };
}
